-- Attendance table: one row per student per group per date
create table if not exists attendance (
    id bigint generated by default as identity primary key,
    student_id uuid not null references profiles(id) on delete cascade,
    group_id uuid not null references groups(id) on delete cascade,
    date date not null,
    status text not null check (status in ('present', 'absent', 'late')) default 'present',
    recorded_by uuid references profiles(id) on delete set null,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now()),
    unique (student_id, group_id, date)
);

create index if not exists idx_attendance_group_date on attendance(group_id, date);
create index if not exists idx_attendance_student on attendance(student_id);

alter table attendance enable row level security;

-- Teachers: select/insert/update for their groups only
drop policy if exists "Teachers can view attendance for their groups" on attendance;
create policy "Teachers can view attendance for their groups" on attendance
    for select using (
        exists (select 1 from groups where id = group_id and teacher_id = auth.uid())
    );

drop policy if exists "Teachers can insert attendance for their groups" on attendance;
create policy "Teachers can insert attendance for their groups" on attendance
    for insert with check (
        exists (select 1 from groups where id = group_id and teacher_id = auth.uid())
    );

drop policy if exists "Teachers can update attendance for their groups" on attendance;
create policy "Teachers can update attendance for their groups" on attendance
    for update using (
        exists (select 1 from groups where id = group_id and teacher_id = auth.uid())
    );

-- Owners: full access
drop policy if exists "Owners can manage attendance" on attendance;
create policy "Owners can manage attendance" on attendance
    for all using (
        exists (select 1 from profiles where id = auth.uid() and role = 'owner')
    );
