-- Grades table: assessment results per student per group
create table if not exists grades (
    id bigint generated by default as identity primary key,
    student_id uuid not null references profiles(id) on delete cascade,
    group_id uuid not null references groups(id) on delete cascade,
    title text not null,
    score text not null,
    grade_type text check (grade_type in ('cefr', 'ielts', 'test', 'exam', 'quiz', 'homework', 'other')) default 'cefr',
    date date not null default current_date,
    recorded_by uuid references profiles(id) on delete set null,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

create index if not exists idx_grades_student on grades(student_id);
create index if not exists idx_grades_group on grades(group_id);
create index if not exists idx_grades_date on grades(date);

alter table grades enable row level security;

-- Teachers: full access for their groups
drop policy if exists "Teachers can view grades for their groups" on grades;
create policy "Teachers can view grades for their groups" on grades
    for select using (
        exists (select 1 from groups where id = group_id and teacher_id = auth.uid())
    );

drop policy if exists "Teachers can insert grades for their groups" on grades;
create policy "Teachers can insert grades for their groups" on grades
    for insert with check (
        exists (select 1 from groups where id = group_id and teacher_id = auth.uid())
    );

drop policy if exists "Teachers can update grades for their groups" on grades;
create policy "Teachers can update grades for their groups" on grades
    for update using (
        exists (select 1 from groups where id = group_id and teacher_id = auth.uid())
    );

drop policy if exists "Teachers can delete grades for their groups" on grades;
create policy "Teachers can delete grades for their groups" on grades
    for delete using (
        exists (select 1 from groups where id = group_id and teacher_id = auth.uid())
    );

-- Students: view own grades only
drop policy if exists "Students can view own grades" on grades;
create policy "Students can view own grades" on grades
    for select using (auth.uid() = student_id);

-- Owners: full access
drop policy if exists "Owners can manage grades" on grades;
create policy "Owners can manage grades" on grades
    for all using (
        exists (select 1 from profiles where id = auth.uid() and role = 'owner')
    );
