-- ============================================
-- MASTER SCHEMA FIX & SYSTEM SYNC
-- ============================================

-- 1. FIX PROFILES TABLE
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT timezone('utc'::text, now());
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS student_code text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS monthly_fee numeric DEFAULT 0;

-- Ensure all roles are lowercase to match application logic
UPDATE public.profiles SET role = LOWER(role) WHERE role IS NOT NULL;

-- 2. ENSURE SUBJECTS TABLE (Preferred UUID for consistency with Substring logic)
-- Note: If data exists, conversion is tricky. We'll handle IF NOT EXISTS with UUID.
CREATE TABLE IF NOT EXISTS public.subjects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    price numeric,
    description text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. ENSURE GROUPS TABLE (Preferred UUID)
CREATE TABLE IF NOT EXISTS public.groups (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    subject_id UUID REFERENCES public.subjects(id),
    teacher_id UUID REFERENCES public.profiles(id),
    time text,
    schedule_days text[],
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. ENSURE ENROLLMENTS TABLE
CREATE TABLE IF NOT EXISTS public.enrollments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    group_id UUID REFERENCES public.groups(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(student_id, group_id)
);

-- 5. ENSURE MONTHLY PAYMENTS TABLE (Used by Finance panels)
CREATE TABLE IF NOT EXISTS public.monthly_payments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    payment_month DATE NOT NULL,
    amount numeric NOT NULL,
    paid_amount numeric DEFAULT 0,
    paid_date timestamp with time zone,
    due_date date,
    status text DEFAULT 'pending' CHECK (status IN ('paid', 'pending', 'overdue')),
    final_amount numeric GENERATED ALWAYS AS (amount) STORED,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(student_id, payment_month)
);

-- 6. ENSURE ATTENDANCE TABLE
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    group_id UUID NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status text NOT NULL CHECK (status IN ('present', 'absent', 'late')) DEFAULT 'present',
    recorded_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    UNIQUE (student_id, group_id, date)
);

-- 7. ENSURE GRADES TABLE
CREATE TABLE IF NOT EXISTS public.grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    group_id UUID NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
    title text NOT NULL,
    score text NOT NULL,
    grade_type text CHECK (grade_type in ('cefr', 'ielts', 'test', 'exam', 'quiz', 'homework', 'other')) DEFAULT 'cefr',
    date date NOT NULL DEFAULT CURRENT_DATE,
    recorded_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 8. RLS POLICIES (Safety check)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grades ENABLE ROW LEVEL SECURITY;

-- Basic liberal policies for admins/owners
DROP POLICY IF EXISTS "Full access for admins" ON public.profiles;
CREATE POLICY "Full access for admins" ON public.profiles FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('owner', 'admin')));

DROP POLICY IF EXISTS "Public view for profiles" ON public.profiles;
CREATE POLICY "Public view for profiles" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins full access" ON public.subjects;
CREATE POLICY "Admins full access" ON public.subjects FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins full access" ON public.groups;
CREATE POLICY "Admins full access" ON public.groups FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins full access" ON public.enrollments;
CREATE POLICY "Admins full access" ON public.enrollments FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins full access" ON public.monthly_payments;
CREATE POLICY "Admins full access" ON public.monthly_payments FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins full access" ON public.attendance;
CREATE POLICY "Admins full access" ON public.attendance FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admins full access" ON public.grades;
CREATE POLICY "Admins full access" ON public.grades FOR ALL USING (auth.role() = 'authenticated');
