-- =============================================
-- MONTHLY PAYMENT SYSTEM SCHEMA
-- (Strict Business Rules Implementation)
-- =============================================

-- 1. ENUMS & TYPES
DO $$ BEGIN
    CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'overdue', 'partial', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. MONTHLY PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS monthly_payments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    student_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    
    -- The specific month this payment is for (always set to 1st of the month)
    payment_month DATE NOT NULL, 
    
    -- Financials
    amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    discount DECIMAL(10, 2) DEFAULT 0,
    final_amount DECIMAL(10, 2) GENERATED ALWAYS AS (amount - discount) STORED,
    paid_amount DECIMAL(10, 2) DEFAULT 0,
    
    -- Status & Dates
    status payment_status DEFAULT 'pending',
    due_date DATE NOT NULL,
    paid_date TIMESTAMPTZ, -- When it was fully paid
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES profiles(id), -- Admin/System who created it
    
    -- Constraints
    CONSTRAINT unique_monthly_payment UNIQUE (student_id, payment_month),
    CONSTRAINT valid_payment_month CHECK (EXTRACT(DAY FROM payment_month) = 1)
);

-- 3. AUDIT LOGS (Strict Requirement: All actions auditable)
CREATE TABLE IF NOT EXISTS payment_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id UUID REFERENCES monthly_payments(id) ON DELETE CASCADE,
    changed_by UUID REFERENCES profiles(id), -- Who made the change
    action TEXT NOT NULL, -- 'create', 'update', 'delete', 'system_auto'
    old_values JSONB,
    new_values JSONB,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SMS LOGS (Existing or Enhanced)
CREATE TABLE IF NOT EXISTS sms_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    phone TEXT,
    message TEXT,
    status TEXT CHECK (status IN ('sent', 'failed', 'pending')),
    provider TEXT, -- 'eskiz', 'playmobile'
    trigger_event TEXT, -- 'reminder', 'overdue', 'paid'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Safely add trigger_event column if it doesn't exist (Migration)
DO $$ BEGIN
    ALTER TABLE sms_logs ADD COLUMN IF NOT EXISTS trigger_event TEXT;
EXCEPTION
    WHEN duplicate_column THEN null;
END $$;

-- 5. AUTOMATION FUNCTIONS

-- Function to generate next month's payment only if current is PAID
CREATE OR REPLACE FUNCTION generate_next_month_payment(
    p_student_id UUID, 
    p_current_month DATE
) RETURNS VOID AS $$
DECLARE
    v_next_month DATE;
    v_monthly_fee DECIMAL(10,2);
    v_profile_status TEXT;
BEGIN
    -- Calculate next month (1st day)
    v_next_month := p_current_month + INTERVAL '1 month';
    
    -- Get student's current monthly fee
    SELECT monthly_fee, status INTO v_monthly_fee, v_profile_status 
    FROM profiles 
    WHERE id = p_student_id;

    -- STRICT RULE: Only generate if student is Active (or was just Unblocked)
    -- If fee is 0, arguably we still generate a 'paid' record or skip? 
    -- Assuming fee > 0 for paid courses.
    
    IF v_monthly_fee > 0 THEN
        INSERT INTO monthly_payments (
            student_id, 
            payment_month, 
            amount, 
            status, 
            due_date
        ) VALUES (
            p_student_id,
            v_next_month,
            v_monthly_fee,
            'pending',
            v_next_month + INTERVAL '10 days' -- Default due date: 10th of the month
        )
        ON CONFLICT (student_id, payment_month) DO NOTHING;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: When a payment is marked as PAID -> Unblock Student & Generate Next Month
CREATE OR REPLACE FUNCTION on_payment_paid() RETURNS TRIGGER AS $$
BEGIN
    -- Only run if status changed to PAID
    IF OLD.status != 'paid' AND NEW.status = 'paid' THEN
        
        -- 1. Set Paid Date
        NEW.paid_date := NOW();
        
        -- 2. Unblock Student (Set Active)
        UPDATE profiles 
        SET status = 'active', 
            last_payment_date = NOW(),
            next_payment_due_date = (NEW.payment_month + INTERVAL '1 month' + INTERVAL '10 days')
        WHERE id = NEW.student_id;

        -- 3. Generate Next Month's Record automatically
        -- (This ensures the chain continues)
        PERFORM generate_next_month_payment(NEW.student_id, NEW.payment_month);
        
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_payment_paid ON monthly_payments;
CREATE TRIGGER trigger_payment_paid
    BEFORE UPDATE ON monthly_payments
    FOR EACH ROW
    WHEN (NEW.status = 'paid')
    EXECUTE FUNCTION on_payment_paid();

-- Trigger: Audit Logging
CREATE OR REPLACE FUNCTION log_payment_changes() RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO payment_audit_logs (payment_id, changed_by, action, new_values)
        VALUES (NEW.id, auth.uid(), 'create', row_to_json(NEW));
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO payment_audit_logs (payment_id, changed_by, action, old_values, new_values)
        VALUES (NEW.id, auth.uid(), 'update', row_to_json(OLD), row_to_json(NEW));
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO payment_audit_logs (payment_id, changed_by, action, old_values)
        VALUES (OLD.id, auth.uid(), 'delete', row_to_json(OLD));
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trigger_payment_audit ON monthly_payments;
CREATE TRIGGER trigger_payment_audit
    AFTER INSERT OR UPDATE OR DELETE ON monthly_payments
    FOR EACH ROW
    EXECUTE FUNCTION log_payment_changes();

-- 6. RLS POLICIES
ALTER TABLE monthly_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins full access to monthly_payments" ON monthly_payments;
CREATE POLICY "Admins full access to monthly_payments" ON monthly_payments
    FOR ALL USING (
        EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('owner', 'admin', 'ceo'))
    );

DROP POLICY IF EXISTS "Students view own payments" ON monthly_payments;
CREATE POLICY "Students view own payments" ON monthly_payments
    FOR SELECT USING (
        student_id = auth.uid()
    );

-- 7. MIGRATION / SEED HELPER (Optional: Manual run to start the cycle)
-- Function to initialize current month for all active students (Run once)
CREATE OR REPLACE FUNCTION init_current_month_payments() RETURNS TEXT AS $$
DECLARE
    r RECORD;
    count INT := 0;
    curr_month DATE := date_trunc('month', CURRENT_DATE);
BEGIN
    FOR r IN SELECT id, monthly_fee FROM profiles WHERE role = 'student' AND status = 'active' LOOP
        INSERT INTO monthly_payments (student_id, payment_month, amount, due_date, status)
        VALUES (r.id, curr_month, r.monthly_fee, curr_month + INTERVAL '10 days', 'pending')
        ON CONFLICT DO NOTHING;
        count := count + 1;
    END LOOP;
    RETURN 'Initialized ' || count || ' payments for ' || curr_month;
END;
$$ LANGUAGE plpgsql;
