-- ============================================================
-- PATCH 05: Production SMS System
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1. Add missing columns to sms_logs
ALTER TABLE public.sms_logs
  ADD COLUMN IF NOT EXISTS sent_at      TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS error_message TEXT;

-- Ensure all expected columns exist (for fresh setups)
ALTER TABLE public.sms_logs
  ADD COLUMN IF NOT EXISTS phone         TEXT,
  ADD COLUMN IF NOT EXISTS provider      TEXT,
  ADD COLUMN IF NOT EXISTS trigger_event TEXT;

-- Update status constraint to include all valid values
ALTER TABLE public.sms_logs
  DROP CONSTRAINT IF EXISTS sms_logs_status_check;
ALTER TABLE public.sms_logs
  ADD CONSTRAINT sms_logs_status_check
    CHECK (status IN ('sent', 'failed', 'pending'));

-- Index for fast lookups (spam check + admin logs view)
CREATE INDEX IF NOT EXISTS idx_sms_logs_phone_event
  ON public.sms_logs (phone, trigger_event, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sms_logs_student_created
  ON public.sms_logs (student_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sms_logs_status
  ON public.sms_logs (status, created_at DESC);

-- 2. Create sms_settings table (or add missing columns if it already exists)
CREATE TABLE IF NOT EXISTS public.sms_settings (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.sms_settings
  ADD COLUMN IF NOT EXISTS attendance_sms_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS payment_sms_enabled     BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS late_warning_count      INTEGER NOT NULL DEFAULT 3;

-- Insert default row if table is empty
INSERT INTO public.sms_settings
  (attendance_sms_enabled, payment_sms_enabled, late_warning_count)
SELECT true, true, 3
WHERE NOT EXISTS (SELECT 1 FROM public.sms_settings);

-- RLS for sms_settings — only admins and owners can read/update
ALTER TABLE public.sms_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sms_settings_admin_read ON public.sms_settings;
CREATE POLICY sms_settings_admin_read ON public.sms_settings
  FOR SELECT USING (true); -- service role bypasses RLS anyway

DROP POLICY IF EXISTS sms_settings_admin_write ON public.sms_settings;
CREATE POLICY sms_settings_admin_write ON public.sms_settings
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role IN ('owner', 'admin')
    )
  );

-- RLS for sms_logs — admins/owners can read all
ALTER TABLE public.sms_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sms_logs_admin_read ON public.sms_logs;
CREATE POLICY sms_logs_admin_read ON public.sms_logs
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role IN ('owner', 'admin')
    )
  );

-- Service role can insert logs (edge functions use service role)
DROP POLICY IF EXISTS sms_logs_service_insert ON public.sms_logs;
CREATE POLICY sms_logs_service_insert ON public.sms_logs
  FOR INSERT WITH CHECK (true);
