-- Create a table for public profiles (if not exists)
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  first_name text,
  last_name text,
  role text check (role in ('owner', 'teacher', 'student', 'parent')) default 'student',
  status text check (status in ('pending', 'approved', 'rejected')) default 'pending',
  phone text,
  birth_date date,
  
  constraint username_length check (char_length(full_name) >= 3)
);

-- Row Level Security for Profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Subjects Table
create table if not exists subjects (
    id bigint generated by default as identity primary key,
    name text not null,
    price decimal(10, 2),
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table subjects enable row level security;
create policy "Subjects viewable by everyone" on subjects for select using (true);
create policy "Admins can insert subjects" on subjects for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'owner'));
create policy "Admins can update subjects" on subjects for update using (exists (select 1 from profiles where id = auth.uid() and role = 'owner'));
create policy "Admins can delete subjects" on subjects for delete using (exists (select 1 from profiles where id = auth.uid() and role = 'owner'));

-- Groups Table
create table if not exists groups (
    id bigint generated by default as identity primary key,
    name text not null,
    subject_id bigint references subjects(id) on delete set null,
    teacher_id uuid references profiles(id) on delete set null,
    schedule_days text[], -- Array of days e.g. ['Mon', 'Wed', 'Fri']
    time time,
    created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table groups enable row level security;
create policy "Groups viewable by everyone" on groups for select using (true);
create policy "Admins can manage groups" on groups for all using (exists (select 1 from profiles where id = auth.uid() and role = 'owner'));

-- Student-Group Enrollments (Many-to-Many)
create table if not exists enrollments (
    id bigint generated by default as identity primary key,
    student_id uuid references profiles(id) on delete cascade,
    group_id bigint references groups(id) on delete cascade,
    enrolled_at timestamp with time zone default timezone('utc'::text, now())
);
alter table enrollments enable row level security;
create policy "Enrollments viewable by involved parties" on enrollments for select using (
    auth.uid() = student_id OR
    exists (select 1 from groups where id = group_id and teacher_id = auth.uid()) OR
    exists (select 1 from profiles where id = auth.uid() and role = 'owner')
);
create policy "Admins can manage enrollments" on enrollments for all using (exists (select 1 from profiles where id = auth.uid() and role = 'owner'));

-- Payments Table
create table if not exists payments (
    id bigint generated by default as identity primary key,
    student_id uuid references profiles(id) on delete set null,
    amount decimal(10, 2) not null,
    date date default CURRENT_DATE,
    status text check (status in ('paid', 'pending', 'overdue')) default 'paid',
    type text, -- e.g. 'tuition', 'books'
    created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table payments enable row level security;
create policy "Admins can manage payments" on payments for all using (exists (select 1 from profiles where id = auth.uid() and role = 'owner'));
create policy "Students can view own payments" on payments for select using (auth.uid() = student_id);

